### ISSUE TITLE
RoadMap 

### ISSUE THREAD

**Issue by Arcoz0308** [Arcoz0308/arcscord#13]
# Core
## Command

- [ ] command handler with auto import

## Component

- [ ] component Middleware
- [ ] component handler with auto import

## Event

- [ ] Event handler with auto import

## Task

- [ ] Task handler with auto import

## Other

- [ ] Add docs

**Comment by Arcoz0308** [comment]
V1 released !
